# Generated by Django 3.2.9 on 2022-03-11 02:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Mahasiswa')], default=1, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaindo', models.CharField(max_length=100, verbose_name='Aspek')),
                ('namainggris', models.CharField(max_length=100, verbose_name='Attitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Capaian Pembelajaran Lulusan',
            },
        ),
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Fakultas')),
                ('namasingkat', models.CharField(blank=True, max_length=50, verbose_name='Singkatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fakultas',
            },
        ),
        migrations.CreateModel(
            name='Gelar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namasingkat', models.CharField(max_length=100, verbose_name='Gelar Singkat')),
                ('nama', models.CharField(max_length=100, verbose_name='Gelar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gelar Pendidikan',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgllahir', models.DateField(auto_created=True, blank=True, verbose_name='Tgl. Lahir')),
                ('nim', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('tempatlahir', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tem. Lahir')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='PerguruanTinggi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama PT')),
                ('nosk', models.CharField(max_length=150, verbose_name='NO SK')),
                ('logo', models.ImageField(max_length=150, upload_to='logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Kampus',
            },
        ),
        migrations.CreateModel(
            name='SubAspekCpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaindo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Aspek')),
                ('namainggris', models.CharField(max_length=100, verbose_name='Sub Attitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpl', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.cpl')),
            ],
            options={
                'verbose_name_plural': 'Sub Aspek Cpl',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tglluluskuliah', models.DateField(auto_created=True, blank=True, verbose_name='Tanggal Lulus')),
                ('tglmasukkuliah', models.DateField(auto_created=True, blank=True, verbose_name='Tanggal Masuk')),
                ('noseriijazah', models.CharField(blank=True, max_length=150, verbose_name='No. Seri Ijazah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gelar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.gelar', verbose_name='Gelar')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.mahasiswa')),
            ],
            options={
                'verbose_name_plural': 'Data SKPI',
            },
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeprodi', models.CharField(max_length=10, verbose_name='Kode Prodi')),
                ('nama', models.CharField(max_length=150, verbose_name='Program Studi')),
                ('namasingkat', models.CharField(max_length=150, verbose_name='Singkatan')),
                ('jenis', models.CharField(blank=True, max_length=150, verbose_name='Jenis Program Pendidikan')),
                ('jenjang', models.CharField(choices=[('D3', 'DIPLOMA-3'), ('S1', 'STRATA-1'), ('S2', 'STRATA-2'), ('S3', 'STRATA-3')], default='1', max_length=150)),
                ('levelkualifikasi', models.CharField(blank=True, choices=[('1', 'level 1'), ('2', 'level 2'), ('3', 'level 3'), ('4', 'level 4'), ('5', 'level 5'), ('5', 'level 6')], max_length=20, verbose_name='Level Kualifikasi')),
                ('persyaratan', models.CharField(blank=True, max_length=100, verbose_name='Syarat Penerimaan')),
                ('noskakreditasi', models.CharField(blank=True, max_length=20, verbose_name='No.SK Akreditasi')),
                ('nilaiakreditasi', models.CharField(blank=True, max_length=50, verbose_name='Nilai Akreditasi')),
                ('images', models.ImageField(upload_to='images_akreditasi')),
                ('lamastudi', models.CharField(blank=True, max_length=10, verbose_name='Lama Studi')),
                ('sistempenilaian', models.TextField(blank=True, verbose_name='Sistem Penilaian')),
                ('bahasapengantar', models.CharField(blank=True, choices=[('Indonesia', 'Indonesia'), ('English', 'English')], max_length=20, verbose_name='Bahasa Pengantar')),
                ('Pendidikanlanjutan', models.CharField(blank=True, choices=[('D3', 'DIPLOMA-3'), ('S1', 'STRATA-1'), ('S2', 'STRATA-2'), ('S3', 'STRATA-3')], max_length=50, verbose_name='Pindidikan Lanjut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.fakultas')),
            ],
            options={
                'verbose_name_plural': 'Program Studi',
                'unique_together': {('kodeprodi',)},
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tglkegiatan', models.DateField(auto_created=True, blank=True, verbose_name='Tanggal')),
                ('namaprestasi', models.CharField(blank=True, max_length=150, verbose_name='Nama Prestasi')),
                ('penyelenggara', models.CharField(blank=True, max_length=150, verbose_name='Penyelenggara')),
                ('atasnama', models.CharField(blank=True, max_length=150, verbose_name='Atas Nama Pribadi/Instansi')),
                ('tingkat', models.CharField(choices=[('Lokal', 'Lokal'), ('Nasional', 'Nasional'), ('Internasional', 'Internasional')], default='Lokal', max_length=50)),
                ('images', models.ImageField(upload_to='img_prestasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.mahasiswa')),
            ],
            options={
                'verbose_name_plural': 'Prestasi',
            },
        ),
        migrations.CreateModel(
            name='Pelatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tglpelatihan', models.DateField(auto_created=True, verbose_name='Tgl. Pelatihan')),
                ('kegiatan', models.CharField(blank=True, max_length=150, verbose_name='Kegiatan')),
                ('penyelenggara', models.CharField(blank=True, max_length=150, verbose_name='Penyelenggara')),
                ('Status', models.CharField(blank=True, max_length=150, verbose_name='Status')),
                ('imgage', models.ImageField(upload_to='img_pelatihan', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.mahasiswa')),
            ],
            options={
                'verbose_name_plural': 'Pelatihan',
            },
        ),
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=150, verbose_name='Nama Organisasi')),
                ('periode', models.CharField(blank=True, max_length=150, verbose_name='Periode')),
                ('jabatan', models.CharField(blank=True, max_length=150, verbose_name='Jabatan')),
                ('berkaspendukung', models.CharField(blank=True, max_length=150, verbose_name='Berkas Pendukung')),
                ('images', models.ImageField(upload_to='img_organisasi', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.mahasiswa')),
            ],
            options={
                'verbose_name_plural': 'Organisasi',
            },
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='programstudi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.programstudi', verbose_name='Program Studi'),
        ),
        migrations.AddField(
            model_name='gelar',
            name='programstudi',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.programstudi'),
        ),
        migrations.AddField(
            model_name='fakultas',
            name='kampus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.perguruantinggi', verbose_name='Kampus'),
        ),
        migrations.AddField(
            model_name='cpl',
            name='programstudi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.programstudi', verbose_name='Program Studi'),
        ),
        migrations.CreateModel(
            name='AdminHOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mahasiswa',
            unique_together={('nim',)},
        ),
    ]
