# Generated by Django 3.2.9 on 2022-03-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0002_auto_20220315_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='nama',
        ),
    ]
