# Generated by Django 3.2.9 on 2022-03-16 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0007_remove_staff_programstudi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='status',
        ),
        migrations.AddField(
            model_name='staff',
            name='programstudi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.programstudi', verbose_name='Program Studi'),
            preserve_default=False,
        ),
    ]
