# Generated by Django 3.2.9 on 2022-03-16 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0008_auto_20220316_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='programstudi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.programstudi', verbose_name='Program Studi'),
        ),
    ]
