# Generated by Django 3.2.9 on 2022-03-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0009_alter_staff_programstudi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpl',
            name='programstudi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.programstudi', verbose_name='Program Studi'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='gender',
            field=models.CharField(choices=[('LAKI-LAKI', 'LAKI-LAKI'), ('PEREMPUAN', 'PEREMPUAN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
