# Generated by Django 3.2.9 on 2022-03-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0010_auto_20220319_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='tempatlahir',
            field=models.CharField(max_length=200, verbose_name='Tem. Lahir'),
        ),
    ]
