# Generated by Django 3.2.9 on 2022-03-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0012_auto_20220322_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='address',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
