# Generated by Django 3.2.9 on 2022-03-23 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0013_alter_mahasiswa_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='programstudi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.programstudi', verbose_name='Program Studi'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='tempatlahir',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='tgllahir',
            field=models.DateField(auto_created=True, blank=True),
        ),
    ]
