# Generated by Django 4.0.3 on 2022-03-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0014_auto_20220323_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelatihan',
            old_name='imgage',
            new_name='image',
        ),
        migrations.AlterUniqueTogether(
            name='mahasiswa',
            unique_together=set(),
        ),
    ]
