# Generated by Django 4.0.3 on 2022-03-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0015_rename_imgage_pelatihan_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='tempatlahir',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
