# Generated by Django 4.0.3 on 2022-03-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0016_alter_mahasiswa_tempatlahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='tgllahir',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
