# Generated by Django 4.0.3 on 2022-04-13 00:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0017_alter_mahasiswa_tgllahir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelatihan',
            old_name='Status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='gelar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.gelar', verbose_name='Gelar'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='noseriijazah',
            field=models.CharField(blank=True, max_length=150, verbose_name='No. Seri Ijazah'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='tglluluskuliah',
            field=models.DateField(auto_created=True, blank=True, default=datetime.datetime(2022, 4, 13, 0, 28, 55, 22955, tzinfo=utc), verbose_name='Tanggal Lulus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='tglmasukkuliah',
            field=models.DateField(auto_created=True, blank=True, default=datetime.datetime(2022, 4, 13, 0, 29, 17, 654064, tzinfo=utc), verbose_name='Tanggal Masuk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skpi',
            name='tglluluskuliah',
            field=models.DateField(auto_created=True, null=True, verbose_name='Tanggal Lulus'),
        ),
        migrations.AlterField(
            model_name='skpi',
            name='tglmasukkuliah',
            field=models.DateField(auto_created=True, null=True, verbose_name='Tanggal Masuk'),
        ),
    ]
