# Generated by Django 4.0.3 on 2022-04-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0018_rename_status_pelatihan_status_mahasiswa_gelar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonfirmasiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setuju', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='tglluluskuliah',
            field=models.DateField(auto_created=True, null=True, verbose_name='Tanggal Lulus'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='tglmasukkuliah',
            field=models.DateField(auto_created=True, null=True, verbose_name='Tanggal Masuk'),
        ),
    ]
