# Generated by Django 4.0.3 on 2022-04-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0019_konfirmasidata_alter_mahasiswa_tglluluskuliah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konfirmasidata',
            name='setuju',
            field=models.BooleanField(default=False, help_text='Belum=default, sudah=hidden'),
        ),
    ]
