# Generated by Django 4.0.3 on 2022-04-13 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0020_alter_konfirmasidata_setuju'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konfirmasidata',
            options={'verbose_name_plural': 'Konfirmasi Data'},
        ),
        migrations.AddField(
            model_name='konfirmasidata',
            name='mahasiswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skpi_management_app.mahasiswa'),
        ),
        migrations.AlterField(
            model_name='konfirmasidata',
            name='setuju',
            field=models.BooleanField(default=False),
        ),
    ]
